# ==== Nav link====
nav:
  Home: /
  Archives: /archives
#  Tags: /tags #extra work needed for this to work
#  Catogories: /categories #extra work needed for this to work
# ==== site logo ====
favicon: '/compass/imgs/favicon.ico' #the default favicon, feel free to change


# ==== Table of Content ====
toc:
  list_number_on: false  #if this is set to 'true', headings of your posts should not have numerical ordered added manually. 

# ==== Copyright ====
copyright_on: true
copyright:
  liscense_type: CC BY-NC-SA 4.0
  liscense_link: http://creativecommons.org/licenses/by-nc-sa/4.0/

# ==== Footer Setting ====
inception: 2020年
email_address: 2393999478@qq.com
social_media:
  github:
    name: github
    address: https://github.com/Zhousm0929 # replace this link with yours
    icon: fa-github
  weibo:
    name: weibo
    address: https://weibo.com/u/2863300182?is_all=1#1588644341329
    icon: fa-weibo

# ==== Additional Setting ====
# View Count by busuanzi
busuanzi_on: true # set to false to disable the view count for your site and posts



# Algolia Search
algolia_on: false # set to true to enable seach within your site, note that extra work needed
algolia:
  applicationID:
  apiKey:
  indexName:
  chunkSize: 5000
  field:
    - title
    - path
    - excerpt:strip
    - excerpt